cacheFolder: ./.yarn/cache
enableGlobalCache: false
enableMirror: true
enableTelemetry: false
nodeLinker: node-modules
compressionLevel: mixed
npmRegistryServer: 'https://registry.npmmirror.com'

yarnPath: .yarn/releases/yarn-4.0.2.cjs
