cacheFolder: ./.yarn/cache
enableGlobalCache: false
nodeLinker: node-modules
compressionLevel: mixed

npmRegistryServer: "https://registry.npmmirror.com"

npmScopes:
  canvas:
    npmRegistryServer: "https://registry.npmmirror.com/-/binary/canvas"

#plugins:
#  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
#    spec: "@yarnpkg/plugin-interactive-tools"
#
yarnPath: .yarn/releases/yarn-4.0.2.cjs

