cacheFolder: ./.yarn/cache
enableGlobalCache: false
nodeLinker: node-modules
compressionLevel: mixed

npmRegistryServer: "https://registry.npmmirror.com"

#plugins:
#  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
#    spec: "@yarnpkg/plugin-interactive-tools"
#
#yarnPath: .yarn/releases/yarn-3.6.3.cjs

