compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

cacheFolder: ./.yarn/cache

npmRegistryServer: "https://registry.npmmirror.com/"

#yarnPath: .yarn/releases/yarn-4.0.2.cjs
